/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Arrays;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sergiy
 */
public class SOXReport extends javax.swing.JFrame {
        Connection conn = null;
        ResultSet rs = null;
        PreparedStatement pst = null; 
    /**
     * Creates new form SOXReport
     */
    public SOXReport() {
        initComponents();
        conn = db.java_db();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        setExtendedState(addServer.MAXIMIZED_BOTH);   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_find = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_allowance = new javax.swing.JTable();
        txt_find_server = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_servers = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_date = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        text_date = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Collect  info for server by ID");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Fine server");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Server name");

        txt_find.setText("*");

        table_allowance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_allowance);

        txt_find_server.setText("alt-sgt%");

        jLabel3.setText("Find server name");

        table_servers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_servers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_serversMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_servers);

        table_date.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_dateMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_date);

        jLabel5.setText("Availbale Date");

        jButton4.setText("Find date entries");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Save report to Excel file");

        jButton5.setText("Main menu");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_find_server))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(3, 3, 3)
                                .addComponent(text_date, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txt_find, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_find_server, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(text_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{

            
            if(!txt_find.getText().trim().equals("")) {
//String sql = "SELECT\n" +
//"trs.system_name, tcs.user_name, tcs.gecos, tcs.supl_groups, tcs.home_dir, tcs.lastlog_user, trs.server_name, tcs.date_entry\n" +
//"\n" +
//"FROM \"tab_main_resp_server\" \"trs\", \"tab_collect_statistic\" \"tcs\" where trs.id_server='" + txt_find.getText() + "' and tcs.id_server='" + txt_find.getText() +"' and tcs.date_entry='2019-02-27'"; // + " and tcs.id_server='" + txt_find.getText();
                                
                String sql = "SELECT\n" +
"trs.system_name, tcs.user_name, tcs.gecos, tcs.supl_groups, tcs.home_dir, tcs.lastlog_user, trs.server_name\n" +
"\n" +
"FROM \"tab_main_resp_server\" \"trs\", \"tab_collect_statistic\" \"tcs\" where trs.id_server='" + txt_find.getText() + "' and tcs.id_server='" + txt_find.getText() +"' and tcs.date_entry='" + text_date.getText()  +"'"; // + " and tcs.id_server='" + txt_find.getText();
                //jLabel4.setText(txt_find.getText());
                pst = conn.prepareStatement(sql);

                pst.execute();

                rs = pst.executeQuery();
                table_allowance.setModel(DbUtils.resultSetToTableModel(rs));

            }
            else if (txt_find.getText().contains("%") )  {
                
                
                
                String part = txt_find.getText();
                java.util.List<String> result = Arrays.asList(part.split("\\%"));               
                
                System.out.println(result.get(0));
                
                String sql = "SELECT 	server_name FROM tab_collect_statistic WHERE  \"server_name\"  like '" + result.get(0) + "%'";
                pst = conn.prepareStatement(sql);

                pst.execute();

                rs = pst.executeQuery();
                table_allowance.setModel(DbUtils.resultSetToTableModel(rs));

            }
            else  {
                
                String sql = "SELECT\n" +
"trs.system_name, tcs.user_name, tcs.gecos, tcs.supl_groups, tcs.home_dir, tcs.lastlog_user, trs.server_name, tcs.date_entry\n" +
"\n" +
"FROM \"tab_main_resp_server\" \"trs\", \"tab_collect_statistic\" \"tcs\" where trs.id_server='" + txt_find.getText() +"' and tcs.date_entry='2019-04-05'";
                pst = conn.prepareStatement(sql);

                pst.setString(1,txt_find.getText());
                pst.execute();

                rs = pst.executeQuery();
                table_allowance.setModel(DbUtils.resultSetToTableModel(rs));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally {

            try{
                rs.close();
                pst.close();
            }
            catch(Exception e){

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       try{

            if (txt_find_server.getText().equals("*"))  {
                //JOptionPane.showMessageDialog(null, "Please enter server name");
                
                int row = table_servers.getSelectedRow();  
                String sql = "select id_server, server_name from tab_main_resp_server";
                
                pst = conn.prepareStatement(sql);

                pst.execute();

                rs = pst.executeQuery();
                table_servers.setModel(DbUtils.resultSetToTableModel(rs));

            }
            else if (txt_find_server.getText().contains("%") )  {
                
                
                
                String part = txt_find_server.getText();
                java.util.List<String> result = Arrays.asList(part.split("\\%"));               
                
                System.out.println(result.get(0));
                
                //String sql = "SELECT server_name FROM tab_collect_statistic WHERE  \"server_name\"  like '" + result.get(0) + "%'";
                String sql = "SELECT id_server, server_name FROM tab_main_resp_server WHERE 	 \"server_name\"  like '" + result.get(0) + "%'";
                pst = conn.prepareStatement(sql);

                pst.execute();

                rs = pst.executeQuery();
                table_servers.setModel(DbUtils.resultSetToTableModel(rs));

            }
            else  {
                String sql = "select * from tab_main_resp_server where server_name =?";
                pst = conn.prepareStatement(sql);

                pst.setString(1,txt_find.getText());
                pst.execute();

                rs = pst.executeQuery();
                table_servers.setModel(DbUtils.resultSetToTableModel(rs));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally {

            try{
                rs.close();
                pst.close();
            }
            catch(Exception e){

            }
        }     
   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void table_serversMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_serversMouseClicked
        // TODO add your handling code here:
        int row = table_servers.getSelectedRow();  
        txt_find.setText(table_servers.getModel().getValueAt(row, 0).toString());     //us_id
        //txtuser_l.setText(table_servers.getModel().getValueAt(row, 1).toString());    //user_l
        //txtuser_f.setText(table_servers.getModel().getValueAt(row, 2).toString());    //user_f
        //txtdepartment.setText(table_servers.getModel().getValueAt(row, 3).toString());//department
        //txtregion.setText(table_servers.getModel().getValueAt(row, 4).toString());    //region
        //txtposition.setText(table_servers.getModel().getValueAt(row, 5).toString());  //position
        //txtstatus.setText(table_servers.getModel().getValueAt(row, 6).toString());    //status
        //txtpasswd.setText(.getModel().getValueAt(row, 7).toString());    //passwd
    }//GEN-LAST:event_table_serversMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       try{
                int row = table_servers.getSelectedRow();  
                String sql = "select DISTINCT date_entry from tab_collect_statistic WHERE  \"id_server\"='" + txt_find.getText()  +"'";
                
                pst = conn.prepareStatement(sql);

                pst.execute();

                rs = pst.executeQuery();
                table_date.setModel(DbUtils.resultSetToTableModel(rs));

       }
             catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally {

            try{
                rs.close();
                pst.close();
            }
            catch(Exception e){

            }
       }          
    }//GEN-LAST:event_jButton4ActionPerformed

    private void table_dateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_dateMouseClicked
        // TODO add your handling code here:
        int row = table_date.getSelectedRow();  
        text_date.setText((table_date.getModel().getValueAt(row, 0).toString()));
        //us_id
    }//GEN-LAST:event_table_dateMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        MainMenu j = new MainMenu();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SOXReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SOXReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SOXReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SOXReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SOXReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table_allowance;
    private javax.swing.JTable table_date;
    private javax.swing.JTable table_servers;
    private javax.swing.JTextField text_date;
    private javax.swing.JTextField txt_find;
    private javax.swing.JTextField txt_find_server;
    // End of variables declaration//GEN-END:variables
}
